### ISSUE TITLE
Could not find 'Save' button

### ISSUE THREAD

**Issue by tacotran** [robinnorth/google-migration-utils#13]
It seems related to PR #12 google has updated the save button selector to be named dynamically, rather than something consistent.

In one example it looked like `pane.wfvdle12` where the number after `wfvdle` seems to be an index for the order of the buttons currently on the screen or in the current window.

**Comment by htownley** [comment]
I encountered the same issue when I tried to the run the script recently. Even though the “Save” button was visibility available the script returned an error for “Could not find save button” for every entry.

**Comment by robinnorth** [comment]
Ah, that's annoying! As a workaround, I've changed the save button selector to `button[aria-label="Save"]` instead, but this will require that the Google Maps language be set to English to work.

**Comment by robinnorth** [comment]
@tacotran @htownley try pulling the latest changes and see if this works for you now

**Comment by tacotran** [comment]
Thank you so much! I tried it and it works great!
